# Generated by Django 4.2.3 on 2024-06-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_like_post_profile_relation_delete_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='relatedcom',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='relatedpost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
