# Generated by Django 4.2.3 on 2024-06-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_relation_relatedcom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatedcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentr', to='main.comment')),
                ('relatedpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postr', to='main.post')),
            ],
        ),
    ]
