# Generated by Django 4.2.3 on 2024-06-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='profile',
        ),
    ]
