# Generated by Django 4.2.3 on 2024-06-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_follow_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='value',
            field=models.CharField(choices=[('Following', 'Following'), ('Follow', 'Follow')], max_length=100),
        ),
    ]
