# Generated by Django 4.2.3 on 2024-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_follow_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Your bio on social media', max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='media/profile.png', upload_to='media/img/%y/'),
        ),
    ]
