# Generated by Django 4.2.3 on 2024-06-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profile_bio_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='media/img/24/profile.png', upload_to='media/img/%y/'),
        ),
    ]
